### ISSUE TITLE
About  GPIO PWM FAN

### ISSUE THREAD

**Issue by yyxp1989** [b-morgan/OctoPrint-FanSpeedMirror#2]
Hello I want Set GPIO14 to control PWM fan, 
how to change the py script, can you give me a hint？thanks

**Comment by b-morgan** [comment]
This plugin was written to expose the M106 gcode command parameter (and the M107 gcode command) to a script running on the RPi. The contents of these scripts are the responsibility of the user. I provided the examples in extra to show how I used this plugin to control an Adafruit DC & Stepper Motor Hat using the Python libraries they provided (which have since become obsolete).

For your issue, I suggest you research how to do this from the language of your choice (Python, Perl, C++, etc.). Start with [https://www.raspberrypi.org/documentation/usage/gpio/](https://www.raspberrypi.org/documentation/usage/gpio/) and follow the links there.

As I mentioned above, the examples I provided are now obsolete. The replacement libraries I used are based on [CircuitPython](https://circuitpython.org/), [https://github.com/adafruit/circuitpython](https://github.com/adafruit/circuitpython) using [https://github.com/adafruit/Adafruit_Blinka](https://github.com/adafruit/Adafruit_Blinka).

**Comment by yyxp1989** [comment]
I tried to learn the pigpio library and python to change the script. Now I can control the fan problem through the Raspberry Pi GPIO PWM. Your plugin and examples are very useful, thank you very much

**Comment by b-morgan** [comment]
You are welcome. Glad you got it figured out.
