### ISSUE TITLE
Index Error: list index out of range

### ISSUE THREAD

**Issue by Gibby1999** [b-morgan/OctoPrint-FanSpeedMirror#3]
Hi there!

As I mentioned before I am trying to control a laser by a PWM output from a GPIO pin. I really know near to nothing about python or bash. So far I got the script which I added at the bottom. I am trying to execute it in Putty and it gives me the error:

Traceback (most recent call last):
  File "fan.py", line 8, in <module>
    s = int(sys.argv[1])
IndexError: list index out of range

If I just enter a number for s it works perfectly fine (I am monitoring the pin with an oscilloscope). However I want s to be the number entered behind every M106 command. The PWM output should stay on till the next M106 command is entered therefore the 'while 1:'
I don't know if that is the right way to do it. When I enter the script path in the plugin and then issue a M106 S128 command nothing happens.

fan.py script:

#!/usr/bin/python3
import sys
import time
import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BOARD)
GPIO.setup(11, GPIO.OUT)

s = int(sys.argv[1])
dc = s*100/255

p = GPIO.PWM(11,1000)  # channel=11 frequency=1kHz
p.start(0)
try:
    while 1:
        p.ChangeDutyCycle(dc)
except KeyboardInterrupt:
    pass
p.stop()
GPIO.cleanup()

Please tell me if you need any further information. Thank you for your time! :)

**Comment by b-morgan** [comment]
What command do you type? I would expect something like `./fan.py 128`. This is what the plugin will execute when it sees `M106 S128`.

The script needs execute permissions which can be set with `chmod +x fan.py` from the command line.

**Comment by b-morgan** [comment]
I'm pretty sure the script needs to exit (i.e. the `while 1` loop needs to be removed). Please use the `<>` to insert code so the indentation is preserved. I'm not a Python expert so you'll have to rely on other sources to get the code working from the command line. Once it is working from there, it should work from the plugin.

My examples included a bash script which in addition to calling the python script, printed some debugging information to a file you could examine. You might try using that until you get things working.

**Comment by Gibby1999** [comment]
Ok now I am calling my fan.py script with the fan.sh script:

fan.sh script:

#!/bin/bash
killall fan.py 
echo $1 $2 $3 >>/home/pi/fan.txt
python /home/pi/fan.py $1
exit $?


fan.py script:


#!/usr/bin/python3
import sys
import time
import RPi.GPIO as GPIO
import subprocess
subprocess.Popen(["chmod", "+x", "/home/pi/fan.py"])
GPIO.setmode(GPIO.BOARD)
GPIO.setup(11, GPIO.OUT)



s = int(sys.argv[1])
dc = s*100/255

p = GPIO.PWM(11,1000)  # channel=11 frequency=1kHz
p.start(dc)

time.sleep(100000000000000000000)


and it's working perfectly fine in Putty but it does nothing when running an M106 command in Putty.

**Comment by b-morgan** [comment]
I think you have a basic misunderstanding about how OctoPrint and this plugin work. OctoPrint is the interface between you and your 3D printer (or laser). An object to be printed is usually converted to gcode by a slicer. This gcode will usually contain commands to move the 3D printer nozzle in the X, Y, and Z dimensions and feed (molten) filament through the nozzle as needed to create the object. In addition to these movement commands, gcode contains various other commands that set temperatures, control cooling fans, etc.

I believe that in your case, you have a laser that you are going to move in the X, Y dimensions and instead of feeding filament through the nozzle, you want to control the laser in real time using M106 commands in the gcode file to turn the laser "on" and off (where "on" might have varying degrees of power). I believe that while the laser is "on", the gcode will move it around to create a pattern on the target material. The gcode may turn the laser off, move to a different location, and then turn the laser back on.

If my assumptions are correct, then the gcode needs to be processed by the firmware in the "printer" without unexpected delays. This plugin is designed to mirror the cooling fan settings (via M106 and M107) in the gcode file. The M106 (and M107) commands are executed "instantaneously" but the speed of the fan is maintained by the printer firmware. The scripts executed by this plugin need to behave the same way, make a "instantaneous" change and return. If your script needs to run continuously to maintain the output waveform, then the script this plugin calls needs to pass values to another script which is running constantly in the background.

**Comment by b-morgan** [comment]
> but it does nothing when running an M106 command in Putty.

I don't understand. The M106 command is embedded in a gcode file that is being processed by OctoPrint. It has nothing to do with PuTTY.

PuTTY is a Windows SSH client used to open a terminal window on your Raspberry Pi (or equivalent).

**Comment by Gibby1999** [comment]
Sorry I didn't mean putty but octoprint.. my bad :/

The way you described how to control the laser is exactly the way I want it! But the issue is that I can't get a clean PWM signal out of my Ender 3. That's why I hoped to be successfull with this plugin. Right now it's running perfectly fine in Putty but when I issue a M106 command in Octoprint it does nothing.

**Comment by b-morgan** [comment]
Are you "printing" a gcode file with an `M106` command in it or just typing the `M106` in the terminal? You need to create a gcode file with the command in it and print that. Nothing will (or should) happen when you type it into the terminal.

The second issue is, of course, that your current script is probably going to stop (or do something else nasty to) the gcode file that is "printing".

**Comment by Gibby1999** [comment]
Ok so now it works as intended for the first M106 command but as you already said it stops the gcode after this. I need a possibility to keep the PWM running until a new M106 command is issued... Do you have an idea if that is possible?

**Comment by b-morgan** [comment]
I believe that you need to use "linux interprocess communication mechanisms in python" (use a Google search). The plugin will call a script that sends the value via one of these mechanisms to a second process that has a loop checking for communications from the plugin and maintaining the PWM from the previous communication. Here is a [link](https://codecalamity.com/interprocess-communications/) that has some examples.

**Comment by Gibby1999** [comment]
I don't think I can realise this script the way I want it. I am going to look for another way to control this laser. But I really appreciate your help! Thank you!
